"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""
import glob

from setuptools import setup

APP = ['app/youtupy.py']
DATA_FILES = [
    ('static', glob.glob('static/jordan.png'))
]

OPTIONS = {
    'packages': ['Cryptodome'],
    'iconfile': 'static/jordan.icns',
    'plist': {
        'CFBundleDevelopmentRegion': 'English',
        'CFBundleIdentifier': 'Zadorozhnyi',
        'CFBundleVersion': '0.0.1',
        'NSHumanReadableCopyright': (
            u'Copyright © 2022, Zadorozhnyi, All Rights Reserved'
        )
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
