DEFAULT_PLAYLIST_PATH = 'playlists'
RETRY_AMOUNT = 3

FIRST = 0
PLAYLIST_URL = 0
INPUT_URL = 0
VID_NAME = 0
PLAYLIST_PATH = 1
DESTINATION_PATH = 1
WITHOUT_SCRIPT_NAME = 1
DOWNLOAD_TYPE = 2
EXTENSION = 3
